name: Automated API tests using Postman CLI Day 2

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 2,12,22 * *"

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "11643422-35d43bee-04cd-4521-a417-9325eee02daa"
