name: Automated API tests using Postman CLI Day 4

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 4,14,24 * *"

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "11643422-a71daa2b-34b2-407b-8eef-dd2631bfb018"
