name: Automated API tests using Postman CLI Day 9

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 9,19,29 * *"
    
jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "11643422-9ffef37e-354c-4a48-9cda-c82360154413"
